### ISSUE TITLE
How to test multiple URLs at once?

### ISSUE THREAD

**Issue by t880216t** [sitespeedio/onlinetest#18]
Can the command line support testing multiple urls at once? Can this webpage be implemented? I haven't found a configuration method, please advise.

**Comment by soulgalore** [comment]
If you want to test on desktop/emulated mobile, you need to deploy multiple testrunners. One test runner can then take on one job at a time. If you setup https://github.com/sitespeedio/onlinetest/blob/main/testrunner/config/default.yaml#L4 to be the same name, the will take on work on the same queue.
