### ISSUE TITLE
Running Test with TestType as Emulated Mobile from UI is running it on Desktop viewport

### ISSUE THREAD

**Issue by Ankit3794** [sitespeedio/onlinetest#75]
From onlinetest UI - Run any URL test with Test Type selected as `Emulated mobile`

**Expected Result**
- URL should be opening with emulated mobile

**Actual**
- report shows screenshot and video with Desktop viewport

![image](https://github.com/user-attachments/assets/024281af-b40b-45d6-ac74-4fc86d7032d1)

![image](https://github.com/user-attachments/assets/ae9c284c-b316-4824-81fa-6171ba801f4f)

OS - Ubuntu
Running Server and TestRunner with Node.Js

**Comment by soulgalore** [comment]
Hi @Ankit3794 that's for the report, it seems like a bug in the GUI. I personally only use the API through sitespeed.io so there must been a changed that broke it. I'll fix it this weekend, I'll ping the issue when its done.

**Comment by Ankit3794** [comment]
yes right, It's bug from UI, as passing --mobile from API works correctly

**Comment by soulgalore** [comment]
@Ankit3794 this is fixed in 0.4.1, thank you for filing the issue!
